# Generated by Django 3.2.8 on 2021-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licapi', '0002_auto_20211103_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editedTimes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
