# Generated by Django 3.2.8 on 2021-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licapi', '0003_user_editedtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='obtainedTimes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
